version: '3'
services:
  database:
    image: postgres:15
    environment:
      # To avoid the following error:
      #
      #   Error: Database is uninitialized and superuser password is not
      #   specified.  You must specify POSTGRES_PASSWORD for the superuser. Use
      #   "-e POSTGRES_PASSWORD=password" to set it in "docker run".
      #
      #   You may also use POSTGRES_HOST_AUTH_METHOD=trust to allow all
      #   connections without a password. This is *not* recommended. See
      #   PostgreSQL documentation about "trust"
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

  conjur:
    image: cyberark/conjur:edge
    command: server
    environment:
      DATABASE_URL: postgres://postgres@database/postgres
      CONJUR_DATA_KEY: 
      CONJUR_AUTHENTICATORS: authn-jwt/circleci1
    depends_on: [ database ]
    ports:
      - "80"

  conjur-server:
    image: nginx:alpine
    ports:
      - 443
    volumes:
      - ./test/https_config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./test/https_config/conjur.conf:/etc/nginx/sites-enabled/conjur.conf:ro
      - ./test/https_config/dhparams.pem:/etc/nginx/dhparams.pem:ro
      - ./test/https_config/conjur.crt:/cert/tls.crt:ro
      - ./test/https_config/conjur.key:/cert/tls.key:ro
      - ./test/https_config/ca.crt:/ca/tls.crt:ro
    depends_on: [ conjur ]